allowBuilds:
  '@firebase/util': set this to true or false
  '@mongodb-js/zstd': set this to true or false
  better-sqlite3: set this to true or false
  bufferutil: set this to true or false
  kerberos: set this to true or false
  libpq: set this to true or false
  mongodb-client-encryption: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
  sqlite3: set this to true or false
